export const SET_EVENTS = "SET_EVENTS"
export const SET_LOADING = "SET_LOADING"
export const SET_SHOWCASE = "SET_SHOWCASE"
export const SET_KEYWORD = "SET_KEYWORD"
export const SET_EVENT = "SET_EVENT"
export const RESET_LOADING = "RESET_LOADING"
